
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavComponent from './components/navigation/nav'
import { AuthProvider } from "./appContexts/AuthContext";
import { LoaderProvider } from "./appContexts/AppLoader";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <AuthProvider>
            <body className={`${inter.className}`}>
              <LoaderProvider>
                <NavComponent/>
                <div className=" min-h-screen flex items-center justify-center bg-gray-900">
                  {children}
                </div>
              </LoaderProvider>
            </body>
      </AuthProvider>
    </html>
  );
}
